### ISSUE TITLE
Bindable picker doesn't work with ObservableCollection changes

### ISSUE THREAD

**Issue by GalFriD** [NaylahProject/Naylah#3]
On the pickers preview on the sample app, 3 persons are added to the viewModel's list but the picker is empty (the label above does work).

**Comment by angusbreno** [comment]
Yes, i see it. 
Thats because the original Xamarin cast items change get not fired. See https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/PickerRenderer.cs#L46

In iOS i've made a custom renderer that's why work in iOS https://github.com/NaylahProject/Naylah/blob/master/Naylah.Xamarin.iOS/Renderers/PickerRenderer.cs#L75

I will fix that, while this u can easily workaround it with:
```
var personsList = new ObservableCollection<Person>();
personsList.Add(new Person() { Name = "Peter" });
personsList.Add(new Person() { Name = "Joana" });
personsList.Add(new Person() { Name = "Naylah" });
PersonsList = personsList;
```

**Comment by GalFriD** [comment]
Perfect, thanks a lot!
